### ISSUE TITLE
本地运行不了，请问怎么本地怎么跑起来，把图片拉到本地

### ISSUE THREAD

**Issue by gtdalp** [zhaojunlike/nodejs-meizitu#1]
本地运行不了，请问怎么本地怎么跑起来，把图片拉到本地

PS D:\my\nodejs-meizitu> node app.js
一共有:undefined个页面需要采集
exit
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to redis-db:6379 failed - getaddrinfo ENOTFOUND redis-db redis-db:6379
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

**Comment by gtsigner** [comment]
这个需要你配置redis哈，你先安装一个redis

**Comment by gtsigner** [comment]
后续我会提供一个专门的开放版本，这个版本是从docker项目中提取出来的

**Comment by gtsigner** [comment]
我已经生成了一个分支版本，你可以进入autoversion版本用就可以了。记得配置redis
